// Generated by tools/make-verified.mjs from the product link checker. Do not edit by hand.
// r: OK (the page opened and showed the product), BLOCKED (the store stops automated browsers;
// the link comes from the store's own search listing), MOVED or BROKEN. p: the price shown, USD.
export const VERIFIED = {
 "checked": "2026-09-28",
 "links": {
  "https://www.ikea.com/us/en/p/glostad-loveseat-knisa-dark-gray-70489011/": {
   "r": "OK",
   "p": 169
  },
  "https://www.ikea.com/us/en/p/friheten-sleeper-sofa-skiftebo-dark-gray-90341151/": {
   "r": "OK",
   "p": 899
  },
  "https://www.walmart.com/ip/Mainstays-Tatum-Twin-Sleeper-Loveseat-Black/1843310558": {
   "r": "OK"
  },
  "https://www.walmart.com/ip/Mainstays-Tatum-Twin-Sleeper-Loveseat-Dark-Gray/2566202369": {
   "r": "OK"
  },
  "https://www.walmart.com/ip/Mainstays-Tatum-Twin-Sleeper-Loveseat-Beige/9315169932": {
   "r": "OK"
  },
  "https://www.ikea.com/us/en/p/friheten-sleeper-sofa-faringe-light-gray-40551231/": {
   "r": "OK",
   "p": 899
  },
  "https://www.ikea.com/us/en/p/poaeng-armchair-birch-veneer-knisa-light-beige-s59305928/": {
   "r": "OK",
   "p": 149
  },
  "https://www.ikea.com/us/en/p/poaeng-armchair-birch-veneer-hillared-dark-blue-s99305926/": {
   "r": "OK",
   "p": 249
  },
  "https://www.ikea.com/us/en/p/poaeng-armchair-birch-veneer-knisa-black-s79305927/": {
   "r": "OK",
   "p": 149
  },
  "https://www.ikea.com/us/en/p/lack-coffee-table-black-brown-00104291/": {
   "r": "OK",
   "p": 49.99
  },
  "https://www.ikea.com/us/en/p/lack-coffee-table-white-stained-oak-effect-40431535/": {
   "r": "OK",
   "p": 49.99
  },
  "https://www.ikea.com/us/en/p/micke-desk-white-80213074/": {
   "r": "OK",
   "p": 109.99
  },
  "https://www.ikea.com/us/en/p/micke-desk-white-anthracite-10489839/": {
   "r": "OK",
   "p": 84.99
  },
  "https://www.ikea.com/us/en/p/sandsberg-table-black-s29420393/": {
   "r": "OK",
   "p": 69.99
  },
  "https://www.ikea.com/us/en/p/lack-tv-unit-white-90631400/": {
   "r": "OK",
   "p": 24.99
  },
  "https://www.ikea.com/us/en/p/billy-bookcase-oak-effect-10508932/": {
   "r": "OK",
   "p": 89
  },
  "https://www.ikea.com/us/en/p/billy-bookcase-black-oak-effect-40477340/": {
   "r": "OK",
   "p": 89
  },
  "https://www.ikea.com/us/en/p/malm-bed-frame-white-s19931605/": {
   "r": "OK",
   "p": 249
  },
  "https://www.ikea.com/us/en/p/asbygda-foam-mattress-firm-white-10481503/": {
   "r": "OK",
   "p": 249
  },
  "https://www.ikea.com/us/en/p/arstid-floor-lamp-nickel-plated-white-50163867/": {
   "r": "OK",
   "p": 89.99
  },
  "https://www.ikea.com/us/en/p/arstid-floor-lamp-brass-white-60321324/": {
   "r": "OK",
   "p": 89.99
  },
  "https://www.ikea.com/us/en/p/solhetta-led-bulb-e26-450-lumen-globe-opal-10591479/": {
   "r": "OK",
   "p": 2.49
  },
  "https://www.ikea.com/us/en/p/arstid-table-lamp-brass-white-80321380/": {
   "r": "OK",
   "p": 39.99
  },
  "https://www.ikea.com/us/en/p/arstid-table-lamp-nickel-plated-white-60280639/": {
   "r": "OK",
   "p": 39.99
  },
  "https://www.ikea.com/us/en/p/tertial-work-lamp-dark-gray-20355434/": {
   "r": "OK",
   "p": 19.99
  },
  "https://www.ikea.com/us/en/p/tertial-work-lamp-light-blue-70504295/": {
   "r": "OK",
   "p": 19.99
  },
  "https://www.ikea.com/us/en/p/misterhult-pendant-lamp-bamboo-handmade-40441025/": {
   "r": "OK",
   "p": 149.99
  },
  "https://www.ikea.com/us/en/p/lindbyn-mirror-black-30590450/": {
   "r": "OK",
   "p": 29.99
  },
  "https://www.ikea.com/us/en/p/lindbyn-mirror-black-60507204/": {
   "r": "OK",
   "p": 79.99
  },
  "https://www.ikea.com/us/en/p/fjaedrar-inner-cushion-off-white-60262188/": {
   "r": "OK",
   "p": 12
  },
  "https://www.ikea.com/us/en/p/aengslilja-duvet-cover-and-pillowcase-s-white-00318541/": {
   "r": "OK",
   "p": 39.99
  },
  "https://www.ikea.com/us/en/p/aengslilja-duvet-cover-and-pillowcase-s-natural-30591987/": {
   "r": "OK",
   "p": 39.99
  },
  "https://www.ikea.com/us/en/p/aengslilja-duvet-cover-and-pillowcase-s-gray-green-70585183/": {
   "r": "OK",
   "p": 39.99
  },
  "https://www.ikea.com/us/en/p/aengslilja-duvet-cover-and-pillowcase-s-blue-gray-40585226/": {
   "r": "OK",
   "p": 39.99
  },
  "https://www.ikea.com/us/en/p/raecka-curtain-rod-combination-white-s59929243/": {
   "r": "OK",
   "p": 15
  },
  "https://www.ikea.com/us/en/p/vagsjoen-hand-bath-towel-set-s39505985/": {
   "r": "OK",
   "p": 25.96
  },
  "https://www.article.com/product/27057/sven-72-tufted-loveseat-stone-gray": {
   "r": "OK",
   "p": 1099
  },
  "https://www.article.com/product/27067/sven-72-tufted-loveseat-biscuit-cream": {
   "r": "OK",
   "p": 1099
  },
  "https://www.article.com/product/24831/sven-72-tufted-velvet-loveseat-plush-pacific-ginger": {
   "r": "OK",
   "p": 1199
  },
  "https://www.article.com/product/27056/sven-88-tufted-sofa-stone-gray": {
   "r": "OK",
   "p": 1299
  },
  "https://www.article.com/product/27069/sven-88-tufted-sofa-biscuit-cream": {
   "r": "OK",
   "p": 1299
  },
  "https://www.article.com/product/27068/sven-88-tufted-sofa-fir-green": {
   "r": "OK",
   "p": 1299
  },
  "https://www.article.com/product/24751/sven-88-tufted-velvet-sofa-plush-pacific-green": {
   "r": "OK",
   "p": 1399
  },
  "https://www.article.com/product/21475/gabriola-34-lounge-chair-ivory-boucle": {
   "r": "OK",
   "p": 499
  },
  "https://www.article.com/product/22235/gabriola-34-lounge-chair-sandstone-wool-boucle": {
   "r": "OK",
   "p": 499
  },
  "https://www.article.com/product/21477/gabriola-34-lounge-chair-dover-gray-boucle": {
   "r": "OK",
   "p": 499
  },
  "https://www.article.com/product/29182/gabriola-34-lounge-chair-green-wool-boucle": {
   "r": "OK",
   "p": 499
  },
  "https://www.article.com/product/29856/amoeba-35-5-round-coffee-table-walnut": {
   "r": "OK",
   "p": 299
  },
  "https://www.article.com/product/24417/lenia-53-5-oval-coffee-table-walnut": {
   "r": "OK",
   "p": 399
  },
  "https://www.article.com/product/25370/lenia-storage-side-table-walnut": {
   "r": "OK",
   "p": 349
  },
  "https://www.article.com/product/24976/hurley-8-x-10-performance-rug-beige-fleck": {
   "r": "OK",
   "p": 499
  },
  "https://www.article.com/product/23754/hira-8-x-10-rug-natural-ivory": {
   "r": "OK",
   "p": 999
  },
  "https://www.article.com/product/18011/jokuna-47-5-media-unit-walnut": {
   "r": "OK",
   "p": 799
  },
  "https://www.article.com/product/3568/crescent-floor-lamp-black": {
   "r": "OK",
   "p": 299
  },
  "https://www.article.com/product/24795/felix-72-media-unit-walnut": {
   "r": "OK",
   "p": 1099
  },
  "https://www.article.com/product/24946/todd-table-lamp-black": {
   "r": "OK",
   "p": 99
  },
  "https://www.article.com/product/18786/moon-table-lamp-gold": {
   "r": "OK",
   "p": 129
  },
  "https://www.article.com/product/18736/gemma-pendant-lamp-brass": {
   "r": "OK",
   "p": 199
  },
  "https://www.article.com/product/18737/gemma-pendant-lamp-black": {
   "r": "OK",
   "p": 199
  },
  "https://www.article.com/product/18738/gemma-pendant-lamp-green": {
   "r": "OK",
   "p": 199
  },
  "https://www.article.com/product/12215/suru-small-pendant-lamp": {
   "r": "OK",
   "p": 199
  },
  "https://www.article.com/product/18769/newberry-31-25-wide-bookcase-walnut": {
   "r": "OK",
   "p": 799
  },
  "https://www.target.com/p/asymmetrical-olive-tree-threshold-8482-designed-with-studio-mcgee/-/A-94685925": {
   "r": "OK"
  },
  "https://www.target.com/p/30-34-x-30-34-beautiful-brushwork-framed-canvas-threshold-8482-designed-with-studio-mcgee/-/A-81785395": {
   "r": "OK"
  },
  "https://www.article.com/product/25637/basi-queen-bed-frame-walnut": {
   "r": "OK",
   "p": 399
  },
  "https://www.target.com/p/36-34-x-36-34-dreary-abstract-landscape-framed-wall-canvas-threshold-8482-designed-with-studio-mcgee/-/A-79502253": {
   "r": "OK"
  },
  "https://www.article.com/product/23863/leesa-studio-queen-mattress": {
   "r": "OK",
   "p": 599
  },
  "https://www.article.com/product/26893/cooper-6-drawer-double-dresser-walnut": {
   "r": "OK",
   "p": 999
  },
  "https://www.article.com/product/26897/cooper-1-drawer-nightstand-walnut": {
   "r": "OK",
   "p": 299
  },
  "https://www.article.com/product/25779/kouva-47-bench-natural-oak-and-santolina-gray": {
   "r": "OK",
   "p": 499
  },
  "https://www.article.com/product/18766/newberry-43-25-desk-walnut": {
   "r": "OK",
   "p": 499
  },
  "https://www.ikea.com/us/en/p/markus-office-chair-vissle-dark-gray-90289172/": {
   "r": "OK",
   "p": 299.99
  },
  "https://www.ikea.com/us/en/p/flintan-office-chair-with-armrests-beige-s49424465/": {
   "r": "OK",
   "p": 119.99
  },
  "https://www.article.com/product/27599/seno-71-dining-table-walnut": {
   "r": "OK",
   "p": 799
  },
  "https://www.ikea.com/us/en/p/flintan-office-chair-with-armrests-black-s29424471/": {
   "r": "OK",
   "p": 119.99
  },
  "https://www.article.com/product/24358/nosh-dining-chair-walnut-and-chalk-gray": {
   "r": "OK",
   "p": 149
  },
  "https://www.article.com/product/24359/nosh-dining-chair-walnut-and-hemlock-green": {
   "r": "OK",
   "p": 149
  },
  "https://www.article.com/product/25750/liv-58-sideboard-walnut": {
   "r": "OK",
   "p": 1099
  },
  "https://www.article.com/product/24362/nosh-dining-chair-walnut-and-quarry-gray": {
   "r": "OK",
   "p": 149
  },
  "https://www.article.com/product/13687/meron-round-wall-mirror-natural": {
   "r": "OK",
   "p": 249
  },
  "https://www.article.com/product/19331/jadara-peacock-blue-throw": {
   "r": "OK",
   "p": 79
  },
  "https://www.target.com/p/washed-cotton-sateen-duvet-cover-and-sham-set-threshold/-/A-81902448": {
   "r": "OK"
  },
  "https://www.ikea.com/us/en/p/raecka-curtain-rod-combination-black-s99929241/": {
   "r": "OK",
   "p": 15
  },
  "https://www.target.com/p/1pc-light-filtering-linen-window-curtain-panel-threshold/-/A-54168343": {
   "r": "OK"
  },
  "https://www.target.com/p/threshold-6-pack-performance-plus-bath-towel-white/-/A-95033971": {
   "r": "OK"
  },
  "https://www.dwr.com/living-lounge-chairs/reid-armchair/2188.html?lang=en_US": {
   "r": "BLOCKED",
   "p": 5795
  },
  "https://www.dwr.com/living-accent-coffee-tables/noguchi-table/6115.html?lang=en_US": {
   "r": "OK",
   "p": 3495
  },
  "https://www.dwr.com/living-side-end-tables/saarinen-side-table/2264.html?lang=en_US": {
   "r": "BLOCKED",
   "p": 1383
  },
  "https://www.dwr.com/rug-type-area-rug/jude-handloom-wool-rug/2567197.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/living-sofas-sectionals/reid-sofa/476317.html?lang=en_US": {
   "r": "OK",
   "p": 9695
  },
  "https://www.dwr.com/storage-credenzas-sideboards/line-credenza/5157.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/lighting-floor/arco-floor-lamp/780.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/lighting-ceiling/nelson-saucer-bubble-pendant/6241.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/lighting-table-lamps/tolomeo-desk-lamp/7468.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/storage-shelving-systems/string-wall-shelving/2198146.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/accessories-art/organic-forms-poster/2540051.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bedroom-beds/matera-bed/5114.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bedroom-mattresses-pillows/sonno-m-mattress/2516559.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bedroom-bedside-tables/matera-bedside-table/991.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bedroom-dressers-armoires/nelson-thin-edge-double-dresser/3650.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/living-benches-stools/nelson-platform-bench/1022.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/office-desks/nelson-swag-leg-desk/6255.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/office-chairs/aeron-chair/100077379.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/kitchen-dining-tables/saarinen-dining-table/7204.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/kitchen-dining-chairs-benches/wishbone-chair/2582.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/mirrors-wall-mirrors/adnet-round-mirror/705.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bath/string-bathroom-shelving/2551983.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/pillows-throws-pillows/oona-pillow/2549900.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/pillows-throws-throw-blankets/oona-alpaca-throw/2527699.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bedding-sheets/design-within-reach-duvet-cover---linen/2577776.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/accessories-bath/dwr-aerocotton-towel-set/10008815.html?lang=en_US": {
   "r": "BLOCKED"
  },
  "https://www.dwr.com/bath-towels/dwr-aerocotton-bathmat/6643.html": {
   "r": "BLOCKED"
  },
  "https://www.ikea.com/us/en/p/flintan-office-chair-black-90489029/": {
   "r": "OK",
   "p": 99.99
  },
  "https://www.ikea.com/us/en/p/flintan-office-chair-beige-00492205/": {
   "r": "OK",
   "p": 99.99
  },
  "https://www.ikea.com/us/en/p/billy-bookcase-white-20522046/": {
   "r": "OK",
   "p": 79
  },
  "https://www.article.com/product/29757/gabriola-pillow-set-ivory-boucle": {
   "r": "OK",
   "p": 79
  },
  "https://www.article.com/product/29758/gabriola-pillow-set-sandstone-wool-boucle": {
   "r": "OK",
   "p": 79
  },
  "https://www.dwr.com/lighting-table-lamps/tolomeo-parchment-shade-lamp/2514057.html?lang=en_US": {
   "r": "BLOCKED"
  }
 }
};
